scope: llantapp
name: node2
restapi:
  listen: 0.0.0.0:8009
  connect_address: node2:8009
etcd:
  hosts: etcd1:2379,etcd2:2379,etcd3:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_node_count: 1
    postgresql:
      parameters:
        wal_level: replica
        hot_standby: on
        max_wal_senders: 10
        max_replication_slots: 10
        shared_buffers: 512MB
        max_connections: 200
        synchronous_commit: on
        synchronous_standby_names: '*'
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    replicator:
      password: replicator
      options:
        - replication
    postgres:
      password: 1234
postgresql:
  listen: 0.0.0.0:5432
  connect_address: node2:5432
  data_dir: /var/lib/postgresql/data
  authentication:
    replication:
      username: replicator
      password: replicator
    superuser:
      username: postgres
      password: 1234
  parameters:
    shared_preload_libraries: 'pg_stat_statements'
