scope: llantapp
name: node1

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008

raft:
  self_addr: 127.0.0.1:7001
  partner_addrs:
    - 127.0.0.1:7002
    - 127.0.0.1:7003

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_node_count: 1
    postgresql:
      parameters:
        wal_level: replica
        hot_standby: on
        max_wal_senders: 10
        max_replication_slots: 10
        shared_buffers: 512MB
        max_connections: 200
        synchronous_commit: on
        synchronous_standby_names: '*'
        shared_preload_libraries: 'pg_stat_statements'
        password_encryption: scram-sha-256
  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 127.0.0.1:5433
  connect_address: 127.0.0.1:5433
  data_dir: C:/llantapp/patroni/node1/data
  parameters:
    shared_preload_libraries: 'pg_stat_statements'
  pg_hba:
    - host all all 127.0.0.1/32 scram-sha-256
    - host replication replicator 127.0.0.1/32 scram-sha-256